package hk.judiciary.icmssvd.model.courtCase.constant;

public enum CaseTypeConstant {
	CIVIL_ACTION ("CJ"),
	CRIMINAL_CASE ("CC"),
	HAWKER_CASE ("HW"),
	DEPARTMENTAL_SUMMONS ("S"),
	DEPARTMENTAL_NOTICE ("N"),
	DRIVING_OFFENCE_POINTS_SUMMONS ("D"),
	FIXED_PENALTY_SUMMONS_GENERIC ("FS"),
	FIXED_PENALTY_SUMMONS_PARKING ("K"),
	FIXED_PENALTY_SUMMONS_MOVING ("V"),
	FIXED_PENALTY_SUMMONS_ANTI_LITTER ("R"),
	FIXED_PENALTY_NOTICE_OF_ORDER_GENERIC ("FN"),
	FIXED_PENALTY_NOTICE_OF_ORDER_PARKING ("P"),
	FIXED_PENALTY_NOTICE_OF_ORDER_MOVING ("M"),
	FIXED_PENALTY_NOTICE_OF_ORDER_ANTI_LITTER ("L"),
	WITNESS_SUMMONS ("Z"),
	LESSER_OFFENCE_REPORT ("LO"),
	//FIXME: THE FOLLOWING ARE NEEDED, PLEASE FILL IN THE REPORT TYPE IF POSSIBLE
	SERVICE_HISTORY_RECORD("SERVICE_HISTORY_RECORD"),
	CHECKLIST_FOR_BATCH_PRINTING_OF_FRESH_SUMMONS ("S-SER"),
	CHECKLIST_OF_NON_SERVICE ("CHECKLIST_OF_NON_SERVICE"),
	CHECKLIST_OF_FIXED_PENALTY_EX_PARTE_APPLICATION ("CHECKLIST_OF_FIXED_PENALTY_EX_PARTE_APPLICATION"),
	CERTIFICATE_OF_BULKING_POSTING ("CERTIFICATE_OF_BULKING_POSTING"),
	CERTIFICATE_OF_POSTING ("CERTIFICATE_OF_POSTING"),
	CERTIFICATE_OF_SERVICE ("CERTIFICATE_OF_SERVICE");
	
	private String code;
	
	private CaseTypeConstant(String code) {
		this.code = code;
	}
	public String getCode() {
		return code;
	}
}
